// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:289449706588:web:5fb103a86599efdfcfd299',
    messagingSenderId: '289449706588',
    projectId: 'aitakata-app',
    authDomain: 'aitakata-app.firebaseapp.com',
    storageBucket: 'aitakata-app.appspot.com',
    measurementId: 'G-ZN7HZDX5XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:289449706588:android:01f5543a3d4d88f0cfd299',
    messagingSenderId: '289449706588',
    projectId: 'aitakata-app',
    storageBucket: 'aitakata-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:289449706588:ios:fe63b4be15be868ccfd299',
    messagingSenderId: '289449706588',
    projectId: 'aitakata-app',
    storageBucket: 'aitakata-app.appspot.com',
    iosBundleId: 'com.example.aitakataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY'),
    appId: '1:289449706588:ios:d4f5f3e75cdab860cfd299',
    messagingSenderId: '289449706588',
    projectId: 'aitakata-app',
    storageBucket: 'aitakata-app.appspot.com',
    iosBundleId: 'com.example.aitakataApp.RunnerTests',
  );
}
